server:
  port: 9000
spring:
  application:
    name: coupon-gateway

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

# 网关配置
zuul:
  prefix: /imooc
  routes:
    # 优惠券模板路由配置定义
    template:
      path: /coupon-template/**
      serviceId: eureka-client-coupon-template
      strip-prefix: false
    host:
      connect-timeout-millis: 15000
      socket-timeout-millis: 60000

#  负载均衡配置
ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000

